# config.yaml


api_key: "123"

sports:
  
  americanfootball:             
    id: "4391"                  
    name: "NFL"
    season: "2025"   

  collegefootball:              
    id: "4479"
    name: "NCAA College Football"
    season: "2025"    

  baseball: 
    id: "4424" 
    name: "MLB"  
    season: "2025"           
  
  basketball: 
    id: "4387"
    name: "NBA"
    season: "2025-2026"

  # englandrugby: 
  #   id: "137123" 
  #   name: "England International Rugby"
  #   season: "2025"

  football: 
    id: "4328"
    name: "Premier League Football"
    season: "2025-2026"

  formula1: 
    id: "4370" 
    name: "Formula 1"
    season: "2025"               

  vitalityblast: 
    id: "4463" 
    name: "County Cricket T20 VB"
    season: "2025"

  thehundred:
    id: "5177"         
    name: "The Hundred"
    season: "2025"

teams:
# English Premier League
  arsenal: "133604"       # Arsenal - Premier League
# NFL Teams
  patriots: "134920"      # New England Patriots
# NBA Teams
  celtics: "134860"       # Boston Celtics
# MLB Teams
  redsox: "135252"       # Boston Red Sox
  
