# config.yaml

api_key: "123"

sports:
  football: "4328"              # British Football
  basketball: "4387"            # NBA
  americanfootball: "4391"      # NFL
  hockey: "4380"                # NHL
  formula1: "4370"              # F1
  baseball: "4424"              # MLB

teams:
  arsenal: "133604"       # Arsenal - Premier League
  patriots: "134920"      # New England Patriots
  celtics: "134860"       # Boston Celtics
  redsox: "135252"       # Boston Red Sox
  
